---
name: PerlCritic

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:

  check:
    name: Check with PerlCritic
    runs-on: ubuntu-latest
    steps:
    - name: Set REPOSITORY
      run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> "${GITHUB_ENV}"
    - name: Check out
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Install PerlCritic
      run: |
        sudo apt update -y
        sudo apt install libperl-critic-perl
    - name: Run PerlCritic
      run: perlcritic ${REPOSITORY}
